// Set up font awesome library and import icons
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faTractor,
  faTimesCircle,
  faPlug,
  faChartLine,
  faHeart,
  faFileAlt,
  faLink,
  faFileInvoiceDollar,
  faRocket,
  faLongArrowAltUp,
  faLongArrowAltDown,
  faQuestionCircle,
  faVideo,
  faWifi,
  faStar,
  faCalendarAlt,
  faCodeBranch,
  faExternalLinkAlt,
  faThumbtack,
  faExclamationTriangle,
  faGavel,
} from '@fortawesome/free-solid-svg-icons';
import {
  faGithub,
  faTwitter,
  faDiscord,
} from '@fortawesome/free-brands-svg-icons';
library.add(
  faTractor,
  faTimesCircle,
  faPlug,
  faChartLine,
  faHeart,
  faGithub,
  faTwitter,
  faDiscord,
  faFileAlt,
  faLink,
  faFileInvoiceDollar,
  faRocket,
  faLongArrowAltUp,
  faLongArrowAltDown,
  faQuestionCircle,
  faVideo,
  faWifi,
  faStar,
  faCalendarAlt,
  faCodeBranch,
  faExternalLinkAlt,
  faThumbtack,
  faExclamationTriangle,
  faGavel,
);
